In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1, 11)
arr1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr2 = np.random.randint(1, 101, size=(3, 3))  # числа 1..100
arr2


array([[89, 73, 73],
       [91, 45, 49],
       [68, 36, 63]])

In [4]:
sum_val = arr1.sum()
mean_val = arr1.mean()
max_val = arr1.max()

sum_val, mean_val, max_val


(np.int64(55), np.float64(5.5), np.int64(10))

In [5]:
arr1_times2 = arr1 * 2
arr1_times2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr1_replaced = arr1.copy()
arr1_replaced[arr1_replaced > 5] = 0
arr1_replaced


array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])